create table public.suppliers (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores, name text not null, unique(store_id, name));
create table public.supplier_deliveries (id uuid primary key, store_id uuid not null references public.stores, supplier_id uuid not null references public.suppliers, product_id uuid not null references public.products, quantity integer not null check (quantity > 0), unit_cost_kobo bigint not null check (unit_cost_kobo >= 0), received_by uuid not null references public.profiles, received_at timestamptz not null default now());
create table public.product_price_history (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores, product_id uuid not null references public.products, previous_cost_kobo bigint not null, new_cost_kobo bigint not null, changed_by uuid not null references public.profiles, changed_at timestamptz not null default now());
alter table public.suppliers enable row level security; alter table public.supplier_deliveries enable row level security; alter table public.product_price_history enable row level security;
create policy "staff see store suppliers" on public.suppliers for select using (store_id = public.current_store_id());
create policy "staff see store deliveries" on public.supplier_deliveries for select using (store_id = public.current_store_id());
create policy "staff see price history" on public.product_price_history for select using (store_id = public.current_store_id());
create or replace function public.record_stock_delivery(p_delivery jsonb) returns void language plpgsql security definer set search_path = public as $$ declare s uuid; r public.app_role; supplier uuid; old_cost bigint; begin select store_id, role into s,r from public.profiles where id=auth.uid(); if s is null or r not in ('admin','manager') then raise exception 'Not permitted'; end if; if exists(select 1 from public.supplier_deliveries where id=(p_delivery->>'id')::uuid) then return; end if; insert into public.suppliers(store_id,name) values(s,p_delivery->>'supplier_name') on conflict(store_id,name) do update set name=excluded.name returning id into supplier; select cost_price_kobo into old_cost from public.products where id=(p_delivery->>'product_id')::uuid and store_id=s for update; if not found then raise exception 'Product not found'; end if; update public.products set stock_quantity=stock_quantity+(p_delivery->>'quantity')::int,cost_price_kobo=(p_delivery->>'unit_cost_kobo')::bigint,updated_at=now() where id=(p_delivery->>'product_id')::uuid; insert into public.supplier_deliveries(id,store_id,supplier_id,product_id,quantity,unit_cost_kobo,received_by) values((p_delivery->>'id')::uuid,s,supplier,(p_delivery->>'product_id')::uuid,(p_delivery->>'quantity')::int,(p_delivery->>'unit_cost_kobo')::bigint,auth.uid()); if old_cost<>(p_delivery->>'unit_cost_kobo')::bigint then insert into public.product_price_history(store_id,product_id,previous_cost_kobo,new_cost_kobo,changed_by) values(s,(p_delivery->>'product_id')::uuid,old_cost,(p_delivery->>'unit_cost_kobo')::bigint,auth.uid()); end if; insert into public.stock_movements(store_id,product_id,quantity_delta,reason,client_operation_id) values(s,(p_delivery->>'product_id')::uuid,(p_delivery->>'quantity')::int,'delivery',gen_random_uuid()); end $$;
grant execute on function public.record_stock_delivery(jsonb) to authenticated;
